### ISSUE TITLE
 CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by hyzgogogo** [Show-han/Zeroshot_REC#3]
![image](https://github.com/Show-han/Zeroshot_REC/assets/169801670/7eda01bd-e24e-43de-b7e2-c74a7c4dddd7)
I encountered this error when executing the following command:
python eval_refcoco/main.py --input_file /data2/yizhi.hu/zeroshot_rec_datasets/reclip_data/refcocog_val.jsonl --image_root /data2/yizhi.hu/zeroshot_rec_datasets/coco2014_image/train2014/train2014 --method matching --clip_model ViT-B/32 --triplets_file /data1/yizhi.hu/zeroshot_rec/Zeroshot_REC/triplets/gpt_refcocog_val.jsonl --detector_file /data2/yizhi.hu/zeroshot_rec_datasets/reclip_data/refcocog_dets_dict.json

**Comment by hyzgogogo** [comment]
Maybe there's a problem with incomplete pictures? I have the full reclip_data folder, but there are some images in the coco_train2014 folder that failed to extract.

**Comment by Show-han** [comment]
I'm not sure what caused this because I haven't encountered this issue before. It seems to be either an environmental issue or possibly what you mentioned.
Does the error occur immediately upon running, or did it appear after running for a while?

**Comment by hyzgogogo** [comment]
The error occured immediately, maybe I should lower some parameters? But  the default batchsize is already 1.
![image](https://github.com/Show-han/Zeroshot_REC/assets/169801670/16f4b56e-62bf-4f0c-aa81-57224a358193)

**Comment by Show-han** [comment]
What GPU are you using?

**Comment by hyzgogogo** [comment]
Thanks for your quick reply. The issue was resolved when I added the CUDA_LAUNCH_BLOCKING=1 command.
