### ISSUE TITLE
Unknown file "hico_verb_names.json" for VLM finetune

### ISSUE THREAD

**Issue by wangzhongqi16** [Show-han/Zeroshot_REC#4]
Dear authors of Zeroshot_REC: 
  When reproducing the VLM finetune experiments, I come across this problem that the file "hico_verb_names.json" is absent in mostly used annotation folders of HICO dataset provided by other HOI projects. 
  Is this file "hico_verb_names.json" customized for this project or is it available? 
  It would be very helpful if you could response to this message. Thank you!

**Comment by Show-han** [comment]
Could you please try create this file using the following content:

`{"verb_names": ["__background__", "adjust", "assemble", "block", "blow", "board", "break", "brush_with", "buy", "carry", "catch", "chase", "check", "clean", "control", "cook", "cut", "cut_with", "direct", "drag", "dribble", "drink_with", "drive", "dry", "eat", "eat_at", "exit", "feed", "fill", "flip", "flush", "fly", "greet", "grind", "groom", "herd", "hit", "hold", "hop_on", "hose", "hug", "hunt", "inspect", "install", "jump", "kick", "kiss", "lasso", "launch", "lick", "lie_on", "lift", "light", "load", "lose", "make", "milk", "move", "no_interaction", "open", "operate", "pack", "paint", "park", "pay", "peel", "pet", "pick", "pick_up", "point", "pour", "pull", "push", "race", "read", "release", "repair", "ride", "row", "run", "sail", "scratch", "serve", "set", "shear", "sign", "sip", "sit_at", "sit_on", "slide", "smell", "spin", "squeeze", "stab", "stand_on", "stand_under", "stick", "stir", "stop_at", "straddle", "swing", "tag", "talk_on", "teach", "text_on", "throw", "tie", "toast", "train", "turn", "type_on", "walk", "wash", "watch", "wave", "wear", "wield", "zip"], "coco_names": ["__background__", "person", "bicycle", "car", "motorcycle", "airplane", "bus", "train", "truck", "boat", "traffic light", "fire hydrant", "__background__", "stop sign", "parking meter", "bench", "bird", "cat", "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "__background__", "backpack", "umbrella", "__background__", "__background__", "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat", "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "__background__", "wine glass", "cup", "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli", "carrot", "hot dog", "pizza", "donut", "cake", "chair", "couch", "potted plant", "bed", "__background__", "dining table", "__background__", "__background__", "toilet", "__background__", "tv", "laptop", "mouse", "remote", "keyboard", "cell phone", "microwave", "oven", "toaster", "sink", "refrigerator", "__background__", "book", "clock", "vase", "scissors", "teddy bear", "hair drier", "toothbrush"]}
`

Does this solve your problem?

**Comment by wangzhongqi16** [comment]
Thank you very much!
