### ISSUE TITLE
How to get the same data of ReClip, the related link has expired

### ISSUE THREAD

**Issue by Volta-lemon** [Show-han/Zeroshot_REC#5]
I tried to download the data using gsutil, but there was nothing. I refer to the following link to visit and get the same result:

https://github.com/allenai/reclip/issues/10

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist.</Message>
</Error>

**Comment by Show-han** [comment]
Perhaps I can upload them this weekend if you need.

**Comment by Volta-lemon** [comment]
> Perhaps I can upload them this weekend if you need.

It would be great if you could. Thank you for your contribution!

**Comment by Show-han** [comment]
Uploaded here `[reclip_data.tar.gz](https://huggingface.co/datasets/CresCat01/RefCOCO-Triplets/blob/main/reclip_data.tar.gz)`

**Comment by Volta-lemon** [comment]
Thank you for the reply
