### ISSUE TITLE
Incorrect reproduction results

### ISSUE THREAD

**Issue by iron-wo** [Show-han/Zeroshot_REC#7]
I want to reproduce the results of the method in the paper using CLIP without fine-tuning，as shown in the figure below
![图片](https://github.com/user-attachments/assets/4d967afc-9048-433b-ba35-62a9b92596c4)

I use the following command
"""
python eval_refcoco/main.py --input_file /REC/Zeroshot_REC/data/reclip_data/input_file/refcocog_val.jsonl --image_root /REC/Zeroshot_REC/data/train2014 --method matching --clip_model ViT-B/32 --triplets_file /REC/Zeroshot_REC/data/reclip_data/triplets_file/gpt_refcocog_val.jsonl --detector_file /REC/Zeroshot_REC/data/reclip_data/detector_file/refcocog_dets_dict.json
"""
The results obtained are different from those in the paper
![图片](https://github.com/user-attachments/assets/00cff5be-3129-4d88-b2ef-576074029711)

Is there something wrong with the command I ran?

**Comment by Show-han** [comment]
I think you should add `--rule_filter` command.
